#!/usr/bin/env python

from sys import argv

from github3 import login, GitHub

pattern = argv[1]
gh = login('xiongchiamiov', 'nope')
for repo in gh.iter_repos():
   branch = repo.master_branch
   if branch == '':
      branch = 'master'
   ref = repo.ref('heads/'+branch)
   head = ref.object.sha
   tree = repo.tree(head)
   for entry in tree.tree:
      if entry.path == pattern:
         print(repo.name)
         break

